# Generated by Django 5.1.7 on 2025-03-25 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pup_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 25, 20, 55, 40, 644337, tzinfo=datetime.timezone.utc)),
        ),
    ]
