# Generated by Django 5.1.7 on 2025-03-31 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_article_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-updated', '-created')},
        ),
    ]
