# Generated by Django 5.1.7 on 2025-04-05 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_message_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 5, 10, 28, 8, 324957, tzinfo=datetime.timezone.utc)),
        ),
    ]
